import {exp} from 'react-native-reanimated';

// Register
export const EMPLOYE_REGISTER = 'EMPLOYE_REGISTER';
export const EMPLOYE_REGISTER_SUCCESS = 'EMPLOYE_REGISTER_SUCCESS';
export const EMPLOYE_REGISTER_FAILED = 'EMPLOYE_REGISTER_FAILED';
export const EMPLOYE_REGISTER_RESET_ITEM = 'EMPLOYE_REGISTER_RESET_ITEM';

// Login
export const EMPLOYE_LOGIN = 'EMPLOYE_LOGIN';
export const EMPLOYE_LOGIN_SUCCESS = 'EMPLOYE_LOGIN_SUCCESS';
export const EMPLOYE_LOGIN_FAILED = 'EMPLOYE_LOGIN_FAILED';
export const EMPLOYE_LOGIN_RESET_ITEM = 'EMPLOYE_LOGIN_RESET_ITEM';

// Employe Profile
export const EMPLOYE_PROFILE = 'EMPLOYE_PROFILE';
export const EMPLOYE_PROFILE_SUCCESS = 'EMPLOYE_PROFILE_SUCCESS';
export const EMPLOYE_PROFILE_FAILED = 'EMPLOYE_PROFILE_FAILED';
